config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :transactions
  devise_for :users
  get 'home/about'
  root 'home#index'
  # root 'transactions#index'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    has_many :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :transactions
         has_many :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @account = current_user.accounts.find_by(id: params[:id])
    redirect_to account, notice: "Not authorized to edit this account " if @account.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:balance, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,  keys: [:balance])
      devise_parameter_sanitizer.permit(:account_update, keys: [:balance])
    end
    def after_sign_in_path_for(resource)
      transactions_path
    end
    def after_update_path_for(resource)
      transactions_path(resource)
    end
    
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
    @accounts = Account.all
    total = Transaction.where(user_id: current_user)
    @sum_trans = total.where(user_id: current_user).sum(:amount)
    @current_balance = current_user.balance - @sum_trans
  end


  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    # @transaction = Transaction.new
    @transaction = current_user.transactions.build
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    # @transaction = Transaction.new(transaction_params)
    @transaction = current_user.transactions.build(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @transaction = current_user.transactions.find_by(id: params[:id])
    redirect_to transactions_path, notice: "Not authorized to edit this transaction " if @transaction.nil?
  end
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:date, :name, :description, :amount, :category, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>Balance:</strong>
    <%= account.balance %>
    <strong>User_id:</strong>
    <%= account.user_id %>
  </p>

</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.text_field :balance %>
  </div>

  <div class="form-group mb-3">
  <% form.label :user_id,  style: "display: block" %>
  <%= form.number_field :user_id, id: :account_user_id, class:"form-control", value:current_user.id%>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>

<div id="accounts">
  <% @accounts.each do |account| %>
    <%= render account %>
    <p>
      <%= link_to "Show this account", account %>
    </p>
    hello
  <% end %>
</div>

<%= link_to "New account", new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Destroy this account", @account, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Budget Buddy', root_path, class: 'navbar-brand' %>  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Transactions", transactions_path, class:"nav-link active" %>
        </li>
          <li class="nav-item">
            <%= link_to "New Transaction", new_transaction_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link active" %>
          </li>
          </li>
        <% else %>  
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link active" %>
          </li>
        <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<body>
    
<div class="col-lg-8 mx-auto p-3 py-md-5">
  <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
  
      <span class="fs-4">Budget Buddy Homepage</span>
    </a>
  </header>

  <main>
    <h1>Welcome to Budget Buddy</h1>
    <p class="fs-5 col-md-8">Track and monitor your account and transactions from your individual profile. Sign up or sign in below!</p>

    <div class="mb-5">
    <%= link_to "Go to my transactions", new_user_session_path, class:"btn btn-primary btn-lg" %>

    </div>

    <hr class="col-3 col-md-2 mb-5">

    <div class="row g-5">

      <div class="col-md-6">
        <h2>Show Me What You Got</h2>
        <p>Check out our functionality!</p>
        <ul class="icon-list">
          <li>Enter you account balance</li>
          <li>Add, update, remove and view your transactions</li>
          <li>Budget Buddy will tell you how much money you have (or don't have) left</li>
        </ul>
      </div>
    </div>
  </main>
  

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show mx-5 mt-5" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgetbuddy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header'%>
    <% if notice %>
      <%= render 'layouts/alerts'%>
    <% end %>

    <div class="container mt-5">
      <%= yield %>
    </div>
    
    <%= render 'home/footer'%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mt-5 mb-4">
    <% form.label :date, style: "display: block" %>
    <%= form.date_field :date, class:"form-control"%>
  </div>

  <div class="form-group mb-4">
    <% form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control", placeholder: "Payee/Business" %>
  </div>

  <div class="form-group mb-3">
    <% form.label :description, style: "display: block" %>
    <%= form.text_field :description, class:"form-control", placeholder: "Description" %>
  </div>

  <div class="form-group mb-3">
    <% form.label :amount, style: "display: block" %>
    <%= form.text_field :amount, class:"form-control", placeholder: "Amount" %>
  </div>

  <div class="form-group mb-3">
    <% form.label :category, style: "display: block" %>
    <select class="form-select" <%= form.text_field :category, class:"form-control" %>>
      <option selected disabled>Select Category</option>
      <option value="Housing">Housing</option>
      <option value="Transportation">Transportation</option>
      <option value="Food/Grocery">Food/Grocery</option>
      <option value="Utilities">Utilities</option>
      <option value="Medical">Medical</option>
      <option value="Entertainment">Entertainment</option>
      <option value="Savings">Savings</option>
      <option value="Miscellaneous">Misc</option>
    </select>
  </div>

  <div class="form-group mb-3">
    <% form.label :user_id,  style: "display: block" %>
    <%= form.number_field :user_id, id: :transaction_user_id, class:"form-control", type: :hidden, value:current_user.id%>
  </div>
  
  <div>
    <%= form.submit class: "btn btn-success btn-lg mt-3" %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Date:</strong>
    <%= transaction.date %>
  </p>

  <p>
    <strong>Payee:</strong>
    <%= transaction.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= transaction.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= transaction.amount %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= transaction.category %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Edit Transaction</h1>

<%= render "form", transaction: @transaction %>


<div>
  <%= link_to "Show this transaction", @transaction, class:"btn btn-primary btn-lg my-3" %> |
  <%= link_to "Back to transactions", transactions_path, class:"btn btn-info btn-lg my-3" %>
</div>

app/views/transactions/index.html.erb
<% if user_signed_in? %>
<div class="row">
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Starting Balance</h5>
        <p class="card-text">$<%= current_user.balance %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Total Spent Since Balance Update</h5>
        <p class="card-text">$<%= @sum_trans %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Current Balance</h5>
        <p class="card-text"> $<%= @current_balance %></p>
      </div>
    </div>
  </div>
</div>

<h1 class="mt-5">Transactions</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Category</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
    
    
  
      <% @transactions.each do |transaction| %>
        <% if transaction.user == current_user%>
        <tr>
        <td><%= transaction.date %></td>
        <td><%= link_to transaction.name, transaction %></td>
        <td><%= transaction.description %></td>
        <td>$<%= transaction.amount %></td>
        <td><%= transaction.category %></td>
            <td><%= link_to "Show", transaction, class:"btn btn-outline-primary btn-sm"%></td>
            <td><%= link_to 'Delete', transaction, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to "New transaction", new_transaction_path, class:"btn btn-secondary btn-lg"%>

<% else %>

<h1>Please sign in to view you account and transactions</h1>


<% end %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to Transactions", transactions_path, class:"btn btn-lg btn-secondary" %>
</div>

app/views/transactions/show.html.erb
<div class="p-5 mb-4 text-bg-dark rounded-3">
  <div class="container-fluid py-5">
      <h2 class="display-5 fw-bold mb-4"><%= @transaction.name %></h2>
      <h2><strong>Date:</strong>
      <%= @transaction.date %></h2>
      <h2><strong>Transaction Amount:</strong>
      $<%= @transaction.amount %></h2>
      <h2><strong>Description:</strong>
      <%= @transaction.description %></h2>
      <h3><strong>Category:</strong>
      <%= @transaction.category %></h3>

    <div>
      <%= link_to "Edit this transaction", edit_transaction_path(@transaction), class:"btn btn-info btn-lg my-3" %> 
      <%= button_to "Destroy this transaction", @transaction, method: :delete, class:"btn btn-danger btn-lg mb-3" %>
      <%= link_to "Back to transactions", transactions_path, class:"btn btn-secondary btn-lg" %>
    </div>
  </div>
</div>